### ISSUE TITLE
Docs/Latest Tag Broken

### ISSUE THREAD

**Issue by superfunc** [SciNim/nim-plotly#78]
Currently redirects to a 404 on your site.

That aside,
Thanks for making this super useful library, I really appreciate it.

**Comment by Vindaar** [comment]
Thanks for the notice! The library was only recently moved over to `SciNim` and this is an oversight.
The still (rather basic) docs are hosted here: https://scinim.github.io/nim-plotly/
It links to the index of the docs now, as there currently is no general "documentation" page.

I fixed it in #79.

> Thanks for making this super useful library, I really appreciate it.

Much appreciated!
